CREATE TABLE `properties` (
	`id` serial AUTO_INCREMENT PRIMARY KEY NOT NULL,
	`advertisement_type` varchar(4) NOT NULL,
	`property_type` varchar(20) NOT NULL,
	`postal_code` varchar(10) NOT NULL,
	`state` varchar(50) NOT NULL,
	`city` varchar(50) NOT NULL,
	`district` varchar(50) NOT NULL,
	`street` varchar(50) NOT NULL,
	`street_number` varchar(10) NOT NULL,
	`complement` varchar(50) NOT NULL,
	`useful_area` decimal(10,2) NOT NULL,
	`total_area` decimal(10,2) NOT NULL,
	`bedrooms` int NOT NULL,
	`bathrooms` int NOT NULL,
	`parking_spaces` int NOT NULL,
	`suites` int NOT NULL,
	`title` varchar(100) NOT NULL,
	`description` text NOT NULL,
	`price` decimal(10,2) NOT NULL,
	`condominium` decimal(10,2),
	`iptu` decimal(10,2));
