import { ClerkProvider } from '@clerk/nextjs/app-beta'
import { Inter as FontSans } from 'next/font/google'

import { Footer } from '~/components/Footer'
import { Providers } from '~/components/Providers'
import { cn } from '~/lib/utils'
import './globals.css'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-inter'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={cn(
        'bg-white font-sans text-slate-900 antialiased',
        fontSans.variable
      )}
    >
      <head />
      <ClerkProvider>
        <Providers>
          <body className="min-h-screen">
            {children}
            <Footer />
          </body>
        </Providers>
      </ClerkProvider>
    </html>
  )
}
